### ISSUE TITLE
Outdated QR code on web page

### ISSUE THREAD

**Issue by skywinder** [KrauseFx/user.activity#4]
There is 404 page by following QR on https://krausefx.github.io/user.activity/

**Comment by KrauseFx** [comment]
Oh, haha, didn't even know there was a QR code on there. Do you want to submit a PR for it? :)

**Comment by skywinder** [comment]
Hah, Krause, you're quick. Actually - no. 😉
But as kind of respect to your greatest projects - will do it. With pleasure 👍
